<?php date_default_timezone_set('America/Sao_Paulo');?>
<?php echo $this->doctype();?>
<html lang="pt-br" data-ng-app="R2Site">
    <head>
        <base href="/">
        <meta charset="utf-8">
        <?php echo $this->headTitle('Ecomart')->setSeparator(' - ')->setAutoEscape(false);?>
        <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ;?>

        <!-- Base style -->
        <!-- build:css(public) /css/base.min.css -->
        <?php
        $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('css/screen.css'), 'screen')
        ->prependStylesheet($this->basePath('css/print.css'), 'print');
        echo $this->headLink();
        $this->headLink()->exchangeArray(array());
        ?>
        <!-- endbuild -->
        <!-- Main style -->
        <!-- build:css(public) /css/main.min.css -->
        <?php
        $this->headLink()
        ->prependStylesheet($this->basePath('css/main.css'));
        echo $this->headLink();
        $this->headLink()->exchangeArray(array());
        ?>
        <!-- endbuild -->
        <!-- Third-Party styles -->
        <!-- build:css(public) /css/vendors.min.css -->
        <?php
        $this->headLink()
        ->prependStylesheet($this->basePath('bower_components/angular-block-ui/dist/angular-block-ui.css'))
        ->prependStylesheet($this->basePath('css/barousel.css'))
        ->prependStylesheet($this->basePath('css/easyzoom.css'))
        ->prependStylesheet($this->basePath('bower_components/ngFloatingLabels/src/ng-floating-labels.css'))
        ->prependStylesheet($this->basePath('css/angular-photo-slider.css'))
        ->prependStylesheet($this->basePath('bower_components/ng-dialog/css/ngDialog-theme-default.css'))
        ->prependStylesheet($this->basePath('bower_components/ng-dialog/css/ngDialog.css'))
        ->prependStylesheet($this->basePath('bower_components/angular-ui-notification/dist/angular-ui-notification.css'))
        ->prependStylesheet($this->basePath('bower_components/angular-loading-bar/build/loading-bar.css'));
        echo $this->headLink();
        $this->headLink()->exchangeArray(array());
        ?>
        <!-- endbuild -->
        

        <script src="https://www.youtube.com/iframe_api"></script>
        <script
        src="https://www.google.com/recaptcha/api.js?onload=vcRecaptchaApiLoaded&render=explicit"
        async defer
        ></script>
        
        <script src="/minified/js/site_plugins.min.js"></script>
        <script src="/minified/js/site_angular_and_resources.min.js"></script>
    </head>
    <body data-foundation-init data-polyfiller-init id="layout-site" ng-cloak>
        <div id="loading-bar-container"></div>
        <!-- <div data-ng-cloak class="row">
            <div class="large-3 large-offset-9 columns"><div data-ng-translate-language-select></div></div>
        </div> -->
        <div data-ui-view="header"></div>
        <div data-ui-view="banner"></div>
        <div data-ui-view="sidebar_left"></div>
        <div data-ui-view="content"></div>
        <div data-ui-view="sidebar_right"></div>
        <div data-ui-view="footer"></div>
        <div data-ng-cloak data-ui-view="notification"></div>


        <script type="text/javascript" src="https://stc.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.directpayment.js">
        </script>

        <script src="/minified/js/R2SiteApp.min.js"></script>
        

    </body>
</html>