admin_vendors_css: {
                src: [
                    'public/bower_components/angular-loading-bar/build/loading-bar.css',
                    'public/bower_components/angular-ui-notification/dist/angular-ui-notification.css',
                    'public/bower_components/ngWYSIWYG/dist/editor.min.css',
                    'public/bower_components/ng-dialog/css/ngDialog.css',
                    'public/bower_components/ng-dialog/css/ngDialog-theme-default.css',
                    'public/bower_components/ngFloatingLabels/src/ng-floating-labels.css',
                    'public/bower_components/angular-block-ui/dist/angular-block-ui.css'
                ],
                dest: '.tmp/concat/adminvendors.css'
            },

            admin_plugins_js: {
                src: [
                    'public/public/bower_components/string/dist/string.js',
                    'public/js/plugins/polyfiller.j',
                    'public/js/plugins/underscore.js',
                    'public/js/plugins/foundation/foundation.tabs.js',
                    'public/bower_components/foundation-sites/js/foundation.offcanvas.js',
                    'public/js/plugins/foundation/foundation.accordionMenu.js',
                    'public/js/plugins/foundation/foundation.reveal.js',
                    'public/js/plugins/foundation/foundation.util.timerAndImageLoader.js',
                    'public/js/plugins/foundation/foundation.util.keyboard.js',
                    'public/js/plugins/foundation/foundation.util.box.js',
                    'public/js/plugins/foundation/foundation.dropdownMenu.js',
                    'public/js/plugins/foundation/foundation.util.motion.js',
                    'public/js/plugins/foundation/foundation.util.nest.js',
                    'public/js/plugins/foundation/foundation.util.mediaQuery.js',
                    'public/js/plugins/foundation/foundation.util.triggers.js',
                    'public/js/plugins/foundation/foundation.responsiveMenu.js',
                    'public/js/plugins/foundation/foundation.responsiveToggle.js',
                    'public/js/plugins/foundation/foundation.core.js',
                    'public/bower_components/foundation-sites/dist/foundation.js',
                    'public/js/plugins/jquery.sticky.js',
                    'public/bower_components/jquery/dist/jquery.js'
                ],
                dest: '.tmp/concat/adminplugins.js'
            },

            admin_angular_and_resources_js: {
                src: [
                    'public/bower_components/angular/angular.js'
                    'public/bower_components/angular-animate/angular-animate.js',
                    'public/bower_components/angular-sanitize/angular-sanitize.js',
                    'public/bower_components/angular-breadcrumb/dist/angular-breadcrumb.js',
                    'public/bower_components/angular-resource/angular-resource.js',
                    'public/bower_components/angular-ui-router/release/angular-ui-router.js',
                    'public/bower_components/angular-cookies/angular-cookies.js',
                    'public/bower_components/angular-messages/angular-messages.js',
                    'public/bower_components/angular-favicon/angular-favicon.js',
                    'public/bower_components/angular-i18n/angular-locale_pt-br.js',
                    'public/bower_components/angular-input-masks/angular-input-masks-standalone.js',
                    'public/bower_components/angular-ui-notification/dist/angular-ui-notification.js',
                    'public/bower_components/angular-loading-bar/build/loading-bar.js',
                    'public/bower_components/ngWYSIWYG/dist/wysiwyg.min.js',
                    'public/bower_components/ng-dialog/js/ngDialog.js',
                    'public/bower_components/angular-smart-table/dist/smart-table.js',
                    'public/bower_components/angular-loading-overlay/dist/angular-loading-overlay.js',
                    'public/bower_components/ng-file-upload/ng-file-upload.js',
                    'public/bower_components/ngFloatingLabels/src/ngFloatingLabels.js',
                    'public/bower_components/angular-block-ui/dist/angular-block-ui.js'
                ],
                dest: '.tmp/concat/ng/adminangularandresources.js'
            },

            'R2AdminApp_js': {
                src: [
                    'public/js/app/shared/ConstantsModule.js',
                    'public/js/app/shared/auth/AuthModule.js',
                    'public/js/app/shared/plugins/factories/underscore.js',
                    'public/js/app/shared/plugins/factories/string.js',
                    'public/js/app/shared/filters/StringFilters.js',
                    'public/js/app/shared/filters/TableFilters.js',
                    'public/js/app/shared/directives/PluginsDirectives.js',
                    'public/js/app/shared/directives/DocumentsDirectives.js',
                    'public/js/app/shared/directives/SocialNetworksDirectives.js',
                    'public/js/app/shared/directives/EmailsDirectives.js',
                    'public/js/app/shared/directives/CreditCardsDirectives.js',
                    'public/js/app/shared/directives/TelephonesDirectives.js',
                    'public/js/app/shared/directives/AddressesDirectives.js',
                    'public/js/app/shared/directives/LaguageSelectDirectives.js',
                    'public/js/app/shared/directives/ValidationDirectives.js',
                    'public/js/app/shared/directives/InputDirectives.js',
                    'public/js/app/shared/directives/PersonDirectives.js',
                    'public/js/app/shared/directives/UsersDirectives.js',
                    'public/js/app/shared/directives/LabelDirectives.js',
                    'public/js/app/shared/directives/CompanyDirectives.js',
                    'public/js/app/shared/directives/VideosDirectives.js',
                    'public/js/app/shared/services/BaseServices.js',
                    'public/js/app/shared/services/UserServices.js',
                    'public/js/app/shared/services/AclServices.js',
                    'public/js/app/shared/services/LocaleServices.js',
                    'public/js/app/shared/services/CompanyServices.js',
                    'public/js/app/shared/services/InventoriesServices.js',
                    'public/js/app/admin/R2Admin.js',
                    'public/js/app/admin/services/ComboProductsServices.js'
                    'public/js/app/admin/services/DiscountCouponsServices.js',
                    'public/js/app/admin/services/ImagesServices.js',
                    'public/js/app/admin/services/FeatureGroupsServices.js',
                    'public/js/app/admin/services/FeaturesServices.js',
                    'public/js/app/admin/services/CustomersServices.js',
                    'public/js/app/admin/services/OrderProductStores.js',
                    'public/js/app/admin/services/DepartmentsServices.js',
                    'public/js/app/admin/services/ProductsServices.js',
                    'public/js/app/admin/services/ManufacturersServices.js',
                    'public/js/app/admin/controllers/ComboProductsControllers.js',        
                    'public/js/app/admin/controllers/DiscountCouponsControllers.js',
                    'public/js/app/admin/controllers/InventoriesControllers.js',
                    'public/js/app/admin/controllers/FeaturesControllers.js',
                    'public/js/app/admin/controllers/StatisticsControllers.js',
                    'public/js/app/admin/controllers/CustomersControllers.js',
                    'public/js/app/admin/controllers/SaleOrdersControllers.js',
                    'public/js/app/admin/controllers/ProductOrdersControllers.js',
                    'public/js/app/admin/controllers/DepartmentsControllers.js',
                    'public/js/app/admin/controllers/ProductControllers.js',
                    'public/js/app/admin/controllers/ManufacturersControllers.js',
                    'public/js/app/admin/controllers/UsersControllers.js',
                    'public/js/app/admin/controllers/LayoutControllers.js',
                    'public/js/app/admin/controllers/HomeControllers.js'

                ],
                '.tmp/concat/ng/R2AdminApp.js'
            },